# Use an official Python runtime as a parent image
FROM python:3.10
# Accept build arguments
ARG OPENAI_API_KEY
ARG GTB_ACCESS_TOKEN
# Set them as environment variables if needed in the running container
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV GTB_ACCESS_TOKEN=${GTB_ACCESS_TOKEN}

# Set the working directory in the container
WORKDIR /usr/src/app

# Install Poetry
RUN pip install poetry

# Copy the current directory contents into the container at /usr/src/app
COPY . /usr/src/app

# Copy only pyproject.toml and poetry.lock to cache dependencies installation
COPY pyproject.toml poetry.lock* /usr/src/app/

# Disable virtualenvs creation by Poetry and install dependencies
RUN poetry config virtualenvs.create false \
    && poetry install --no-dev

# Your other commands, like copying source files and setting entrypoint
# COPY . .
# ENTRYPOINT ["your-entrypoint-script-or-command"]

